#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TinTucGD.Models
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLWEBGIAODUC")]
	public partial class dbQLTintucDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertLOAIBAIVIET(LOAIBAIVIET instance);
    partial void UpdateLOAIBAIVIET(LOAIBAIVIET instance);
    partial void DeleteLOAIBAIVIET(LOAIBAIVIET instance);
    partial void InsertADMIN(ADMIN instance);
    partial void UpdateADMIN(ADMIN instance);
    partial void DeleteADMIN(ADMIN instance);
    partial void InsertBAIVIET(BAIVIET instance);
    partial void UpdateBAIVIET(BAIVIET instance);
    partial void DeleteBAIVIET(BAIVIET instance);
    partial void InsertBINHLUAN(BINHLUAN instance);
    partial void UpdateBINHLUAN(BINHLUAN instance);
    partial void DeleteBINHLUAN(BINHLUAN instance);
    partial void InsertDOCGIA(DOCGIA instance);
    partial void UpdateDOCGIA(DOCGIA instance);
    partial void DeleteDOCGIA(DOCGIA instance);
    #endregion
		
		public dbQLTintucDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["QLWEBGIAODUCConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLTintucDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLTintucDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLTintucDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public dbQLTintucDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOAIBAIVIET> LOAIBAIVIETs
		{
			get
			{
				return this.GetTable<LOAIBAIVIET>();
			}
		}
		
		public System.Data.Linq.Table<ADMIN> ADMINs
		{
			get
			{
				return this.GetTable<ADMIN>();
			}
		}
		
		public System.Data.Linq.Table<BAIVIET> BAIVIETs
		{
			get
			{
				return this.GetTable<BAIVIET>();
			}
		}
		
		public System.Data.Linq.Table<BINHLUAN> BINHLUANs
		{
			get
			{
				return this.GetTable<BINHLUAN>();
			}
		}
		
		public System.Data.Linq.Table<CHITIETBAIVIET> CHITIETBAIVIETs
		{
			get
			{
				return this.GetTable<CHITIETBAIVIET>();
			}
		}
		
		public System.Data.Linq.Table<DOCGIA> DOCGIAs
		{
			get
			{
				return this.GetTable<DOCGIA>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOAIBAIVIET")]
	public partial class LOAIBAIVIET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaLoai;
		
		private string _TenLoai;
		
		private EntitySet<BAIVIET> _BAIVIETs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnTenLoaiChanging(string value);
    partial void OnTenLoaiChanged();
    #endregion
		
		public LOAIBAIVIET()
		{
			this._BAIVIETs = new EntitySet<BAIVIET>(new Action<BAIVIET>(this.attach_BAIVIETs), new Action<BAIVIET>(this.detach_BAIVIETs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TenLoai", DbType="NVarChar(50)")]
		public string TenLoai
		{
			get
			{
				return this._TenLoai;
			}
			set
			{
				if ((this._TenLoai != value))
				{
					this.OnTenLoaiChanging(value);
					this.SendPropertyChanging();
					this._TenLoai = value;
					this.SendPropertyChanged("TenLoai");
					this.OnTenLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBAIVIET_BAIVIET", Storage="_BAIVIETs", ThisKey="MaLoai", OtherKey="MaLoai")]
		public EntitySet<BAIVIET> BAIVIETs
		{
			get
			{
				return this._BAIVIETs;
			}
			set
			{
				this._BAIVIETs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BAIVIETs(BAIVIET entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBAIVIET = this;
		}
		
		private void detach_BAIVIETs(BAIVIET entity)
		{
			this.SendPropertyChanging();
			entity.LOAIBAIVIET = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ADMIN")]
	public partial class ADMIN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _UserAdmin;
		
		private string _PasswordAdmin;
		
		private string _Hoten;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnUserAdminChanging(string value);
    partial void OnUserAdminChanged();
    partial void OnPasswordAdminChanging(string value);
    partial void OnPasswordAdminChanged();
    partial void OnHotenChanging(string value);
    partial void OnHotenChanged();
    #endregion
		
		public ADMIN()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UserAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string UserAdmin
		{
			get
			{
				return this._UserAdmin;
			}
			set
			{
				if ((this._UserAdmin != value))
				{
					this.OnUserAdminChanging(value);
					this.SendPropertyChanging();
					this._UserAdmin = value;
					this.SendPropertyChanged("UserAdmin");
					this.OnUserAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_PasswordAdmin", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string PasswordAdmin
		{
			get
			{
				return this._PasswordAdmin;
			}
			set
			{
				if ((this._PasswordAdmin != value))
				{
					this.OnPasswordAdminChanging(value);
					this.SendPropertyChanging();
					this._PasswordAdmin = value;
					this.SendPropertyChanged("PasswordAdmin");
					this.OnPasswordAdminChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Hoten", DbType="NVarChar(50)")]
		public string Hoten
		{
			get
			{
				return this._Hoten;
			}
			set
			{
				if ((this._Hoten != value))
				{
					this.OnHotenChanging(value);
					this.SendPropertyChanging();
					this._Hoten = value;
					this.SendPropertyChanged("Hoten");
					this.OnHotenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BAIVIET")]
	public partial class BAIVIET : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBaiViet;
		
		private string _TuaDe;
		
		private string _TomTatND;
		
		private string _MaLoai;
		
		private string _HinhAnh;
		
		private EntitySet<BINHLUAN> _BINHLUANs;
		
		private EntityRef<LOAIBAIVIET> _LOAIBAIVIET;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBaiVietChanging(string value);
    partial void OnMaBaiVietChanged();
    partial void OnTuaDeChanging(string value);
    partial void OnTuaDeChanged();
    partial void OnTomTatNDChanging(string value);
    partial void OnTomTatNDChanged();
    partial void OnMaLoaiChanging(string value);
    partial void OnMaLoaiChanged();
    partial void OnHinhAnhChanging(string value);
    partial void OnHinhAnhChanged();
    #endregion
		
		public BAIVIET()
		{
			this._BINHLUANs = new EntitySet<BINHLUAN>(new Action<BINHLUAN>(this.attach_BINHLUANs), new Action<BINHLUAN>(this.detach_BINHLUANs));
			this._LOAIBAIVIET = default(EntityRef<LOAIBAIVIET>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiViet", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBaiViet
		{
			get
			{
				return this._MaBaiViet;
			}
			set
			{
				if ((this._MaBaiViet != value))
				{
					this.OnMaBaiVietChanging(value);
					this.SendPropertyChanging();
					this._MaBaiViet = value;
					this.SendPropertyChanged("MaBaiViet");
					this.OnMaBaiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TuaDe", DbType="NVarChar(150)")]
		public string TuaDe
		{
			get
			{
				return this._TuaDe;
			}
			set
			{
				if ((this._TuaDe != value))
				{
					this.OnTuaDeChanging(value);
					this.SendPropertyChanging();
					this._TuaDe = value;
					this.SendPropertyChanged("TuaDe");
					this.OnTuaDeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TomTatND", DbType="NVarChar(MAX)")]
		public string TomTatND
		{
			get
			{
				return this._TomTatND;
			}
			set
			{
				if ((this._TomTatND != value))
				{
					this.OnTomTatNDChanging(value);
					this.SendPropertyChanging();
					this._TomTatND = value;
					this.SendPropertyChanged("TomTatND");
					this.OnTomTatNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaLoai", DbType="VarChar(10)")]
		public string MaLoai
		{
			get
			{
				return this._MaLoai;
			}
			set
			{
				if ((this._MaLoai != value))
				{
					if (this._LOAIBAIVIET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaLoaiChanging(value);
					this.SendPropertyChanging();
					this._MaLoai = value;
					this.SendPropertyChanged("MaLoai");
					this.OnMaLoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HinhAnh", DbType="NVarChar(100)")]
		public string HinhAnh
		{
			get
			{
				return this._HinhAnh;
			}
			set
			{
				if ((this._HinhAnh != value))
				{
					this.OnHinhAnhChanging(value);
					this.SendPropertyChanging();
					this._HinhAnh = value;
					this.SendPropertyChanged("HinhAnh");
					this.OnHinhAnhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIVIET_BINHLUAN", Storage="_BINHLUANs", ThisKey="MaBaiViet", OtherKey="MaBaiViet")]
		public EntitySet<BINHLUAN> BINHLUANs
		{
			get
			{
				return this._BINHLUANs;
			}
			set
			{
				this._BINHLUANs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="LOAIBAIVIET_BAIVIET", Storage="_LOAIBAIVIET", ThisKey="MaLoai", OtherKey="MaLoai", IsForeignKey=true, DeleteRule="CASCADE")]
		public LOAIBAIVIET LOAIBAIVIET
		{
			get
			{
				return this._LOAIBAIVIET.Entity;
			}
			set
			{
				LOAIBAIVIET previousValue = this._LOAIBAIVIET.Entity;
				if (((previousValue != value) 
							|| (this._LOAIBAIVIET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._LOAIBAIVIET.Entity = null;
						previousValue.BAIVIETs.Remove(this);
					}
					this._LOAIBAIVIET.Entity = value;
					if ((value != null))
					{
						value.BAIVIETs.Add(this);
						this._MaLoai = value.MaLoai;
					}
					else
					{
						this._MaLoai = default(string);
					}
					this.SendPropertyChanged("LOAIBAIVIET");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.BAIVIET = this;
		}
		
		private void detach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.BAIVIET = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.BINHLUAN")]
	public partial class BINHLUAN : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaBinhLuan;
		
		private string _NoiDung;
		
		private System.Nullable<System.DateTime> _NgayBinhLuan;
		
		private string _MaBaiViet;
		
		private string _MaDocGia;
		
		private EntityRef<BAIVIET> _BAIVIET;
		
		private EntityRef<DOCGIA> _DOCGIA;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaBinhLuanChanging(string value);
    partial void OnMaBinhLuanChanged();
    partial void OnNoiDungChanging(string value);
    partial void OnNoiDungChanged();
    partial void OnNgayBinhLuanChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayBinhLuanChanged();
    partial void OnMaBaiVietChanging(string value);
    partial void OnMaBaiVietChanged();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    #endregion
		
		public BINHLUAN()
		{
			this._BAIVIET = default(EntityRef<BAIVIET>);
			this._DOCGIA = default(EntityRef<DOCGIA>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBinhLuan", DbType="VarChar(30) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaBinhLuan
		{
			get
			{
				return this._MaBinhLuan;
			}
			set
			{
				if ((this._MaBinhLuan != value))
				{
					this.OnMaBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._MaBinhLuan = value;
					this.SendPropertyChanged("MaBinhLuan");
					this.OnMaBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDung", DbType="NVarChar(MAX)")]
		public string NoiDung
		{
			get
			{
				return this._NoiDung;
			}
			set
			{
				if ((this._NoiDung != value))
				{
					this.OnNoiDungChanging(value);
					this.SendPropertyChanging();
					this._NoiDung = value;
					this.SendPropertyChanged("NoiDung");
					this.OnNoiDungChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayBinhLuan", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayBinhLuan
		{
			get
			{
				return this._NgayBinhLuan;
			}
			set
			{
				if ((this._NgayBinhLuan != value))
				{
					this.OnNgayBinhLuanChanging(value);
					this.SendPropertyChanging();
					this._NgayBinhLuan = value;
					this.SendPropertyChanged("NgayBinhLuan");
					this.OnNgayBinhLuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiViet", DbType="VarChar(20)")]
		public string MaBaiViet
		{
			get
			{
				return this._MaBaiViet;
			}
			set
			{
				if ((this._MaBaiViet != value))
				{
					if (this._BAIVIET.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaBaiVietChanging(value);
					this.SendPropertyChanging();
					this._MaBaiViet = value;
					this.SendPropertyChanged("MaBaiViet");
					this.OnMaBaiVietChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="VarChar(20)")]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					if (this._DOCGIA.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="BAIVIET_BINHLUAN", Storage="_BAIVIET", ThisKey="MaBaiViet", OtherKey="MaBaiViet", IsForeignKey=true, DeleteRule="CASCADE")]
		public BAIVIET BAIVIET
		{
			get
			{
				return this._BAIVIET.Entity;
			}
			set
			{
				BAIVIET previousValue = this._BAIVIET.Entity;
				if (((previousValue != value) 
							|| (this._BAIVIET.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._BAIVIET.Entity = null;
						previousValue.BINHLUANs.Remove(this);
					}
					this._BAIVIET.Entity = value;
					if ((value != null))
					{
						value.BINHLUANs.Add(this);
						this._MaBaiViet = value.MaBaiViet;
					}
					else
					{
						this._MaBaiViet = default(string);
					}
					this.SendPropertyChanged("BAIVIET");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_BINHLUAN", Storage="_DOCGIA", ThisKey="MaDocGia", OtherKey="MaDocGia", IsForeignKey=true, DeleteRule="CASCADE")]
		public DOCGIA DOCGIA
		{
			get
			{
				return this._DOCGIA.Entity;
			}
			set
			{
				DOCGIA previousValue = this._DOCGIA.Entity;
				if (((previousValue != value) 
							|| (this._DOCGIA.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DOCGIA.Entity = null;
						previousValue.BINHLUANs.Remove(this);
					}
					this._DOCGIA.Entity = value;
					if ((value != null))
					{
						value.BINHLUANs.Add(this);
						this._MaDocGia = value.MaDocGia;
					}
					else
					{
						this._MaDocGia = default(string);
					}
					this.SendPropertyChanged("DOCGIA");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CHITIETBAIVIET")]
	public partial class CHITIETBAIVIET
	{
		
		private string _MaBaiViet;
		
		private string _NoiDungChinh;
		
		private System.Nullable<System.DateTime> _NgayDang;
		
		private string _AnhBaiViet;
		
		public CHITIETBAIVIET()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaBaiViet", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string MaBaiViet
		{
			get
			{
				return this._MaBaiViet;
			}
			set
			{
				if ((this._MaBaiViet != value))
				{
					this._MaBaiViet = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NoiDungChinh", DbType="NVarChar(MAX)")]
		public string NoiDungChinh
		{
			get
			{
				return this._NoiDungChinh;
			}
			set
			{
				if ((this._NoiDungChinh != value))
				{
					this._NoiDungChinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDang", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgayDang
		{
			get
			{
				return this._NgayDang;
			}
			set
			{
				if ((this._NgayDang != value))
				{
					this._NgayDang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AnhBaiViet", DbType="NVarChar(100)")]
		public string AnhBaiViet
		{
			get
			{
				return this._AnhBaiViet;
			}
			set
			{
				if ((this._AnhBaiViet != value))
				{
					this._AnhBaiViet = value;
				}
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DOCGIA")]
	public partial class DOCGIA : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _MaDocGia;
		
		private string _HoTenDayDu;
		
		private string _TaiKhoan;
		
		private string _MatKhau;
		
		private string _DiaChi;
		
		private string _Email;
		
		private string _SoDienThoai;
		
		private System.Nullable<System.DateTime> _NgaySinh;
		
		private EntitySet<BINHLUAN> _BINHLUANs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnMaDocGiaChanging(string value);
    partial void OnMaDocGiaChanged();
    partial void OnHoTenDayDuChanging(string value);
    partial void OnHoTenDayDuChanged();
    partial void OnTaiKhoanChanging(string value);
    partial void OnTaiKhoanChanged();
    partial void OnMatKhauChanging(string value);
    partial void OnMatKhauChanged();
    partial void OnDiaChiChanging(string value);
    partial void OnDiaChiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    partial void OnSoDienThoaiChanging(string value);
    partial void OnSoDienThoaiChanged();
    partial void OnNgaySinhChanging(System.Nullable<System.DateTime> value);
    partial void OnNgaySinhChanged();
    #endregion
		
		public DOCGIA()
		{
			this._BINHLUANs = new EntitySet<BINHLUAN>(new Action<BINHLUAN>(this.attach_BINHLUANs), new Action<BINHLUAN>(this.detach_BINHLUANs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MaDocGia", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string MaDocGia
		{
			get
			{
				return this._MaDocGia;
			}
			set
			{
				if ((this._MaDocGia != value))
				{
					this.OnMaDocGiaChanging(value);
					this.SendPropertyChanging();
					this._MaDocGia = value;
					this.SendPropertyChanged("MaDocGia");
					this.OnMaDocGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HoTenDayDu", DbType="NVarChar(50)")]
		public string HoTenDayDu
		{
			get
			{
				return this._HoTenDayDu;
			}
			set
			{
				if ((this._HoTenDayDu != value))
				{
					this.OnHoTenDayDuChanging(value);
					this.SendPropertyChanging();
					this._HoTenDayDu = value;
					this.SendPropertyChanged("HoTenDayDu");
					this.OnHoTenDayDuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TaiKhoan", DbType="VarChar(20)")]
		public string TaiKhoan
		{
			get
			{
				return this._TaiKhoan;
			}
			set
			{
				if ((this._TaiKhoan != value))
				{
					this.OnTaiKhoanChanging(value);
					this.SendPropertyChanging();
					this._TaiKhoan = value;
					this.SendPropertyChanged("TaiKhoan");
					this.OnTaiKhoanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MatKhau", DbType="VarChar(50)")]
		public string MatKhau
		{
			get
			{
				return this._MatKhau;
			}
			set
			{
				if ((this._MatKhau != value))
				{
					this.OnMatKhauChanging(value);
					this.SendPropertyChanging();
					this._MatKhau = value;
					this.SendPropertyChanged("MatKhau");
					this.OnMatKhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DiaChi", DbType="NVarChar(100)")]
		public string DiaChi
		{
			get
			{
				return this._DiaChi;
			}
			set
			{
				if ((this._DiaChi != value))
				{
					this.OnDiaChiChanging(value);
					this.SendPropertyChanging();
					this._DiaChi = value;
					this.SendPropertyChanged("DiaChi");
					this.OnDiaChiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SoDienThoai", DbType="VarChar(50)")]
		public string SoDienThoai
		{
			get
			{
				return this._SoDienThoai;
			}
			set
			{
				if ((this._SoDienThoai != value))
				{
					this.OnSoDienThoaiChanging(value);
					this.SendPropertyChanging();
					this._SoDienThoai = value;
					this.SendPropertyChanged("SoDienThoai");
					this.OnSoDienThoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgaySinh", DbType="DateTime")]
		public System.Nullable<System.DateTime> NgaySinh
		{
			get
			{
				return this._NgaySinh;
			}
			set
			{
				if ((this._NgaySinh != value))
				{
					this.OnNgaySinhChanging(value);
					this.SendPropertyChanging();
					this._NgaySinh = value;
					this.SendPropertyChanged("NgaySinh");
					this.OnNgaySinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DOCGIA_BINHLUAN", Storage="_BINHLUANs", ThisKey="MaDocGia", OtherKey="MaDocGia")]
		public EntitySet<BINHLUAN> BINHLUANs
		{
			get
			{
				return this._BINHLUANs;
			}
			set
			{
				this._BINHLUANs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = this;
		}
		
		private void detach_BINHLUANs(BINHLUAN entity)
		{
			this.SendPropertyChanging();
			entity.DOCGIA = null;
		}
	}
}
#pragma warning restore 1591
