//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAN.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Code
    {
        public long Id { get; set; }
        public string Code1 { get; set; }
        public decimal Price { get; set; }
        public Nullable<bool> Expired { get; set; }
    }
}
